language: groovy

jdk:
  - openjdk7
  - oraclejdk7

env:
- GRAILS_VERSION=3.2.4
- GRAILS_VERSION=3.2.8


before_install:
  - rm -rf ~/.gvm
  - curl -s get.sdkman.io | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  # dev null is to avoid the need for user input https://github.com/sdkman/sdkman-cli/issues/101
  - sdk install grails $GRAILS_VERSION < /dev/null
  - sdk use grails $GRAILS_VERSION
  - grails -version
  - sdk current grails

script: grails clean
     && grails test-app --non-interactive


notifications:
  email: false
  slack: frctristarcollab:jsFS3EN9AbPL31QLUlJL4MTH